Repository saraaa10/zelfzorg-service, pull requests merged in 2022-10, with the labels that each got.

#1 update user repo
  src/main/usecases/user_repository.go
Labels: enhancement

#2 add user type repo
  src/main/usecases/user_type_repository.go
Labels: enhancement

#3 add transaction repo
  src/main/usecases/transaction_repository.go
Labels: enhancement

#4 Develop
  src/main/usecases/transaction_repository.go
  src/main/usecases/user_repository.go
  src/main/usecases/user_type_repository.go
Labels: enhancement

#5 add method new transaction repo
  src/main/usecases/transaction_repository.go
Labels: enhancement

#6 modif architecture main to develop
  app.go
  src/main/adapter/api/transaction_handler.go
  src/main/adapter/api/user_handler.go
  src/main/adapter/api/user_type_handler.go
  src/main/adapter/auth/service_jwt.go
  src/main/app/entities/transaction_entity.go
  src/main/app/entities/user_entity.go
  src/main/app/entities/user_type_entity.go
  src/main/app/repositories/transaction_repository.go
  src/main/app/repositories/user_repository.go
  src/main/app/repositories/user_type_repository.go
  src/main/handlers/transaction_handler.go
  src/main/handlers/user_handler.go
  src/main/handlers/user_type_handler.go
  src/main/infra/database.go
  src/main/infra/middleware.go
  src/main/infra/response_formatter.go
  src/main/infra/viper.go
  src/main/util/transaction_formatter.go
  src/main/util/transaction_input.go
  src/main/util/user_formatter.go
  src/main/util/user_input.go
  src/main/util/user_type_formatter.go
  src/main/util/user_type_input.go
Labels: documentation, enhancement

#7 Add Docker to project
  Dockerfile
  docker-compose-dev.yml
Labels: enhancement

#11 Merged branch main to base repo
  src/main/app/repositories/transaction_repository.go
  src/main/app/repositories/user_repository.go
  src/main/app/repositories/user_type_repository.go
Labels: documentation
